### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by jakehamilton** [imfunniee/NoOS#2]
Hi! I have a few questions about this project.

- What is it supposed to do?
- What platforms are supported?
- How do you build it? Are there any requirements?
- How do I go about making changes?

**Comment by imfunniee** [comment]
sup,

sry for the lateness, didn't thought someone would show interest in this 😂 (or any of my projects 😥)

- so umm it's suppose to be used for customizing/emulating 🤷‍♂️ your OS kinda like [NOVA launcher](https://play.google.com/store/apps/details?id=com.teslacoilsw.launcher&hl=en_GB) but for your pc.
- i have tested this on win, don't about other platforms.
- i build it using electron and you will need nodejs for that. if you don't have it [download](https://nodejs.org/en/) it. once downloaded follow the [getting started](https://github.com/imfunniee/NoOS/blob/master/README.md#getting-started) steps in readme.
- it should be easy if you know html/css/js and all that good good things, just make changes in those files. will advice you to watch [this](https://www.youtube.com/watch?v=kN1Czs0m1SU).

if you came from any of the discord servers (bet its devon's server) and have more questions about it, hmu in dms
